const crypto = require("crypto");

const { redisClient } = require("../config/redis");

// =========================================================
// SESSION CONFIGURATION
// =========================================================
//
// Access Token:
//   Recommended lifetime: 15 minutes
//
// Refresh Session:
//   Default lifetime: 7 days
//
// IMPORTANT:
//   The raw refresh token is NEVER stored in Redis.
//   Only its SHA-256 hash is stored.
//
// =========================================================

const SESSION_TTL_SECONDS =
  Number(process.env.REFRESH_TOKEN_EXPIRES_IN_SECONDS) || 7 * 24 * 60 * 60;

// =========================================================
// HELPER FUNCTIONS
// =========================================================

/**
 * Generate a cryptographically secure session ID.
 *
 * @returns {string}
 */
function generateSessionId() {
  return crypto.randomBytes(32).toString("hex");
}

/**
 * Generate a cryptographically secure refresh token.
 *
 * @returns {string}
 */
function generateRefreshToken() {
  return crypto.randomBytes(64).toString("hex");
}

/**
 * Hash a refresh token before storing/comparing it.
 *
 * @param {string} token
 * @returns {string}
 */
function hashRefreshToken(token) {
  return crypto.createHash("sha256").update(token).digest("hex");
}

/**
 * Generate Redis key for a session.
 *
 * @param {string} sessionId
 * @returns {string}
 */
function getSessionKey(sessionId) {
  return `session:${sessionId}`;
}

/**
 * Validate session ID.
 *
 * Session IDs generated by this service contain
 * exactly 64 hexadecimal characters.
 *
 * @param {string} sessionId
 * @returns {boolean}
 */
function isValidSessionId(sessionId) {
  return typeof sessionId === "string" && /^[a-f0-9]{64}$/i.test(sessionId);
}

/**
 * Normalize session metadata.
 *
 * @param {Object} metadata
 * @returns {Object}
 */
function normalizeMetadata(metadata = {}) {
  return {
    userAgent:
      typeof metadata.userAgent === "string"
        ? metadata.userAgent.slice(0, 1000)
        : "",

    ip: typeof metadata.ip === "string" ? metadata.ip.slice(0, 100) : "",
  };
}

// =========================================================
// CREATE SESSION
// =========================================================

/**
 * Create a new authentication session.
 *
 * The raw refresh token is returned to the controller.
 * The controller should place it inside an HttpOnly cookie.
 *
 * Redis stores only the hash of the refresh token.
 *
 * @param {Object} options
 * @param {string} options.userId
 * @param {string} [options.userAgent]
 * @param {string} [options.ip]
 *
 * @returns {Promise<Object>}
 */
async function createSession({ userId, userAgent = "", ip = "" }) {
  if (!userId) {
    throw new Error("userId is required to create a session");
  }

  const sessionId = generateSessionId();

  const refreshToken = generateRefreshToken();

  const refreshTokenHash = hashRefreshToken(refreshToken);

  const now = new Date();

  const expiresAt = new Date(now.getTime() + SESSION_TTL_SECONDS * 1000);

  const metadata = normalizeMetadata({
    userAgent,
    ip,
  });

  const session = {
    sessionId,

    userId: String(userId),

    refreshTokenHash,

    createdAt: now.toISOString(),

    expiresAt: expiresAt.toISOString(),

    userAgent: metadata.userAgent,

    ip: metadata.ip,
  };

  const sessionKey = getSessionKey(sessionId);

  await redisClient.set(sessionKey, JSON.stringify(session), {
    EX: SESSION_TTL_SECONDS,
  });

  return {
    sessionId,

    refreshToken,

    expiresAt: expiresAt.toISOString(),
  };
}

// =========================================================
// GET SESSION
// =========================================================

/**
 * Get session from Redis.
 *
 * @param {string} sessionId
 * @returns {Promise<Object|null>}
 */
async function getSession(sessionId) {
  if (!isValidSessionId(sessionId)) {
    return null;
  }

  const sessionData = await redisClient.get(getSessionKey(sessionId));

  if (!sessionData) {
    return null;
  }

  try {
    return JSON.parse(sessionData);
  } catch (error) {
    console.error("Session JSON Parse Error:", error);

    // Remove corrupted session.
    await redisClient.del(getSessionKey(sessionId));

    return null;
  }
}

// =========================================================
// VERIFY ACCESS SESSION
// =========================================================

/**
 * Verify that an authentication session is active.
 *
 * IMPORTANT:
 *
 * This function is used by auth.middleware.js.
 *
 * It does NOT verify the refresh token.
 *
 * It verifies:
 *
 * 1. Session ID is valid
 * 2. Redis session exists
 * 3. Session has not expired
 *
 * @param {string} sessionId
 * @returns {Promise<Object|null>}
 */
async function verifyAccessSession(sessionId) {
  // =======================================================
  // 1. VALIDATE SESSION ID
  // =======================================================

  if (!isValidSessionId(sessionId)) {
    return null;
  }

  // =======================================================
  // 2. GET SESSION
  // =======================================================

  const session = await getSession(sessionId);

  if (!session) {
    return null;
  }

  // =======================================================
  // 3. CHECK APPLICATION EXPIRATION
  // =======================================================

  const expiresAt = new Date(session.expiresAt).getTime();

  if (!Number.isFinite(expiresAt) || expiresAt <= Date.now()) {
    await destroySession(sessionId);

    return null;
  }

  // =======================================================
  // 4. RETURN ACTIVE SESSION
  // =======================================================

  return session;
}

// =========================================================
// VERIFY REFRESH SESSION
// =========================================================

/**
 * Verify a refresh token against a Redis session.
 *
 * Checks:
 *
 * 1. Session ID
 * 2. Redis session existence
 * 3. Application-level expiration
 * 4. Refresh-token hash
 *
 * @param {Object} options
 * @param {string} options.sessionId
 * @param {string} options.refreshToken
 *
 * @returns {Promise<Object|null>}
 */
async function verifySession({ sessionId, refreshToken }) {
  if (!sessionId || !refreshToken) {
    return null;
  }

  if (!isValidSessionId(sessionId)) {
    return null;
  }

  const session = await getSession(sessionId);

  if (!session) {
    return null;
  }

  // =======================================================
  // CHECK APPLICATION EXPIRATION
  // =======================================================

  const expiresAt = new Date(session.expiresAt).getTime();

  if (!Number.isFinite(expiresAt) || expiresAt <= Date.now()) {
    await destroySession(sessionId);

    return null;
  }

  // =======================================================
  // HASH INCOMING REFRESH TOKEN
  // =======================================================

  const incomingHash = hashRefreshToken(refreshToken);

  const storedHash = session.refreshTokenHash;

  if (
    typeof storedHash !== "string" ||
    storedHash.length !== incomingHash.length
  ) {
    return null;
  }

  // =======================================================
  // TIMING-SAFE COMPARISON
  // =======================================================

  const hashesMatch = crypto.timingSafeEqual(
    Buffer.from(storedHash, "utf8"),
    Buffer.from(incomingHash, "utf8"),
  );

  if (!hashesMatch) {
    return null;
  }

  return session;
}

// =========================================================
// ROTATE REFRESH TOKEN
// =========================================================

/**
 * Rotate refresh token.
 *
 * The previous refresh token becomes invalid immediately.
 *
 * @param {Object} options
 * @param {string} options.sessionId
 * @param {string} options.currentRefreshToken
 *
 * @returns {Promise<Object|null>}
 */
async function rotateRefreshToken({ sessionId, currentRefreshToken }) {
  const session = await verifySession({
    sessionId,
    refreshToken: currentRefreshToken,
  });

  if (!session) {
    return null;
  }

  // =======================================================
  // GENERATE NEW REFRESH TOKEN
  // =======================================================

  const newRefreshToken = generateRefreshToken();

  const newRefreshTokenHash = hashRefreshToken(newRefreshToken);

  const now = new Date();

  const expiresAt = new Date(now.getTime() + SESSION_TTL_SECONDS * 1000);

  // =======================================================
  // UPDATE SESSION
  // =======================================================

  const updatedSession = {
    ...session,

    refreshTokenHash: newRefreshTokenHash,

    expiresAt: expiresAt.toISOString(),
  };

  await redisClient.set(
    getSessionKey(sessionId),
    JSON.stringify(updatedSession),
    {
      EX: SESSION_TTL_SECONDS,
    },
  );

  return {
    sessionId,

    refreshToken: newRefreshToken,

    expiresAt: expiresAt.toISOString(),
  };
}

// =========================================================
// UPDATE SESSION
// =========================================================

/**
 * Update session metadata.
 *
 * Allowed:
 *   - userAgent
 *   - ip
 *
 * @param {string} sessionId
 * @param {Object} updates
 *
 * @returns {Promise<Object|null>}
 */
async function updateSession(sessionId, updates = {}) {
  const session = await getSession(sessionId);

  if (!session) {
    return null;
  }

  const allowedUpdates = {};

  if (typeof updates.userAgent === "string") {
    allowedUpdates.userAgent = updates.userAgent.slice(0, 1000);
  }

  if (typeof updates.ip === "string") {
    allowedUpdates.ip = updates.ip.slice(0, 100);
  }

  const updatedSession = {
    ...session,
    ...allowedUpdates,
  };

  const expiresAt = new Date(updatedSession.expiresAt).getTime();

  const remainingSeconds = Math.max(
    1,
    Math.ceil((expiresAt - Date.now()) / 1000),
  );

  await redisClient.set(
    getSessionKey(sessionId),
    JSON.stringify(updatedSession),
    {
      EX: Math.min(remainingSeconds, SESSION_TTL_SECONDS),
    },
  );

  return updatedSession;
}

// =========================================================
// DESTROY ONE SESSION
// =========================================================

/**
 * Destroy one session.
 *
 * Used for:
 *   - Normal logout
 *   - Logout from a specific device
 *   - Security revocation
 *
 * @param {string} sessionId
 * @returns {Promise<boolean>}
 */
async function destroySession(sessionId) {
  if (!isValidSessionId(sessionId)) {
    return false;
  }

  const deleted = await redisClient.del(getSessionKey(sessionId));

  return deleted > 0;
}

// =========================================================
// DESTROY ALL USER SESSIONS
// =========================================================

/**
 * Destroy all sessions belonging to a user.
 *
 * Used for:
 *   - Logout all devices
 *   - Password change
 *   - Password reset
 *   - Account security reset
 *
 * @param {string} userId
 * @returns {Promise<number>}
 */
async function destroyAllUserSessions(userId) {
  if (!userId) {
    return 0;
  }

  let cursor = 0;

  let deletedCount = 0;

  do {
    const result = await redisClient.scan(cursor, {
      MATCH: "session:*",
      COUNT: 100,
    });

    cursor = Number(result.cursor);

    const keys = result.keys || [];

    if (keys.length === 0) {
      continue;
    }

    const values = await redisClient.mGet(keys);

    const keysToDelete = [];

    for (let i = 0; i < keys.length; i += 1) {
      const value = values[i];

      if (!value) {
        continue;
      }

      try {
        const session = JSON.parse(value);

        if (String(session.userId) === String(userId)) {
          keysToDelete.push(keys[i]);
        }
      } catch (error) {
        console.error("Invalid Redis session:", error);

        // Remove corrupted session.
        keysToDelete.push(keys[i]);
      }
    }

    if (keysToDelete.length > 0) {
      const deleted = await redisClient.del(keysToDelete);

      deletedCount += deleted;
    }
  } while (cursor !== 0);

  return deletedCount;
}

// =========================================================
// GET USER SESSIONS
// =========================================================

/**
 * Get all active sessions for a user.
 *
 * IMPORTANT:
 * Never expose refreshTokenHash.
 *
 * @param {string} userId
 * @returns {Promise<Array>}
 */
async function getUserSessions(userId) {
  if (!userId) {
    return [];
  }

  const sessions = [];

  let cursor = 0;

  do {
    const result = await redisClient.scan(cursor, {
      MATCH: "session:*",
      COUNT: 100,
    });

    cursor = Number(result.cursor);

    const keys = result.keys || [];

    if (keys.length === 0) {
      continue;
    }

    const values = await redisClient.mGet(keys);

    for (const value of values) {
      if (!value) {
        continue;
      }

      try {
        const session = JSON.parse(value);

        if (String(session.userId) !== String(userId)) {
          continue;
        }

        sessions.push({
          sessionId: session.sessionId,

          createdAt: session.createdAt,

          expiresAt: session.expiresAt,

          userAgent: session.userAgent,

          ip: session.ip,
        });
      } catch (error) {
        console.error("Session JSON Parse Error:", error);
      }
    }
  } while (cursor !== 0);

  return sessions;
}

// =========================================================
// SESSION EXISTS
// =========================================================

/**
 * Check whether a session exists.
 *
 * @param {string} sessionId
 * @returns {Promise<boolean>}
 */
async function sessionExists(sessionId) {
  if (!isValidSessionId(sessionId)) {
    return false;
  }

  const exists = await redisClient.exists(getSessionKey(sessionId));

  return exists === 1;
}

// =========================================================
// EXPORT
// =========================================================

module.exports = {
  SESSION_TTL_SECONDS,

  generateSessionId,
  generateRefreshToken,
  hashRefreshToken,

  createSession,
  getSession,

  // Used by auth.middleware.js
  verifyAccessSession,

  // Used by refresh controller
  verifySession,

  rotateRefreshToken,

  updateSession,

  destroySession,
  destroyAllUserSessions,

  getUserSessions,

  sessionExists,
};
